In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('preprocessedDataset.csv')

In [8]:
df = df.drop(columns = ['Unnamed: 0'])

In [9]:
df

,Age,Income,Female,Male,Austin,Boston,Los Angeles,Mountain View,New York City,San Diego,Washington D.C.,Illness
0,41,40367.0,0,1,0,0,0,0,0,0,0,0
1,54,45084.0,0,1,0,0,0,0,0,0,0,0
2,42,52483.0,0,1,0,0,0,0,0,0,0,0
3,40,40941.0,0,1,0,0,0,0,0,0,0,0
4,46,50289.0,0,1,0,0,0,0,0,0,0,0
5,36,50786.0,1,0,0,0,0,0,0,0,0,0
6,32,33155.0,1,0,0,0,0,0,0,0,0,0
7,39,30914.0,0,1,0,0,0,0,0,0,0,0
8,51,68667.0,0,1,0,0,0,0,0,0,0,0
9,30,50082.0,1,0,0,0,0,0,0,0,0,0
10,48,41524.0,1,0,0,0,0,0,0,0,0,1
11,47,54777.0,0,1,0,0,0,0,0,0,0,0
12,46,62749.0,0,1,0,0,0,0,0,0,0,0
13,42,50894.0,1,0,0,0,0,0,0,0,0,0
14,61,38429.0,1,0,0,0,0,0,0,0,0,0
15,43,34074.0,0,1,0,0,0,0,0,0,0,0
16,27,50398.0,0,1,0,0,0,0,0,0,0,0
17,38,46373.0,0,1,0,0,0,0,0,0,0,1
18,47,51137.0,0,1,0,0,0,0,0,0,0,0
19,35,23688.0,1,0,0,0,0,0,0,0,0,0
20,57,17378.0,0,1,0,0,0,0,0,0,0,0
21,33,45919.0,0,1,0,0,0,0,0,0,0,0
22,33,23001.0,1,0,0,0,0,0,0,0,0,0
23,27,34292.0,1,0,0,0,0,0,0,0,0,1
24,58,55190.0,0,1,0,0,0,0,0,0,0,0
25,64,26169.0,0,1,0,0,0,0,0,0,0,0
26,58,57322.0,0,1,0,0,0,0,0,0,0,0
27,44,61704.0,0,1,0,0,0,0,0,0,0,0
28,34,53619.0,0,1,0,0,0,0,0,0,0,0
29,45,47421.0,0,1,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
149970,63,99950.0,1,0,1,0,0,0,0,0,0,0
149971,30,76928.0,1,0,1,0,0,0,0,0,0,0
149972,46,84395.0,0,1,1,0,0,0,0,0,0,0
149973,52,77272.0,1,0,1,0,0,0,0,0,0,0
149974,39,90430.0,1,0,1,0,0,0,0,0,0,0
149975,51,92132.0,1,0,1,0,0,0,0,0,0,0
149976,49,91519.0,0,1,1,0,0,0,0,0,0,0
149977,51,107123.0,0,1,1,0,0,0,0,0,0,0
149978,58,100949.0,0,1,1,0,0,0,0,0,0,0
149979,43,86737.0,0,1,1,0,0,0,0,0,0,0
149980,53,89384.0,1,0,1,0,0,0,0,0,0,1
149981,50,77134.0,0,1,1,0,0,0,0,0,0,0
149982,47,92157.0,1,0,1,0,0,0,0,0,0,0
149983,25,92482.0,1,0,1,0,0,0,0,0,0,0
149984,51,99075.0,0,1,1,0,0,0,0,0,0,0
149985,25,74947.0,1,0,1,0,0,0,0,0,0,0
149986,63,80381.0,1,0,1,0,0,0,0,0,0,0
149987,55,62501.0,1,0,1,0,0,0,0,0,0,0
149988,26,77823.0,1,0,1,0,0,0,0,0,0,0
149989,52,83688.0,0,1,1,0,0,0,0,0,0,0
149990,26,82163.0,1,0,1,0,0,0,0,0,0,0
149991,51,97510.0,0,1,1,0,0,0,0,0,0,0
149992,37,88408.0,0,1,1,0,0,0,0,0,0,0
149993,64,89906.0,0,1,1,0,0,0,0,0,0,0
149994,37,106097.0,1,0,1,0,0,0,0,0,0,0
149995,48,93669.0,0,1,1,0,0,0,0,0,0,0
149996,25,96748.0,0,1,1,0,0,0,0,0,0,0
149997,26,111885.0,0,1,1,0,0,0,0,0,0,0
149998,25,111878.0,0,1,1,0,0,0,0,0,0,0
149999,37,87251.0,1,0,1,0,0,0,0,0,0,0

In [36]:
y = df['Illness'].iloc[:].values

In [37]:
X = df.iloc[:,:-1].values

In [38]:
X[0]

array([4.1000e+01, 4.0367e+04, 0.0000e+00, 1.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00])

In [39]:
y[0]

0

In [40]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [41]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=10)
classifier.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [42]:
print(classifier.score(X_test, y_test, sample_weight=None))
from sklearn.metrics import classification_report
y_pred = classifier.predict(X_test)
print(classification_report(y_true=y_test,y_pred = y_pred))

0.8809292929292929
              precision    recall  f1-score   support

           0       0.92      0.95      0.94     45547
           1       0.08      0.05      0.06      3953

   micro avg       0.88      0.88      0.88     49500
   macro avg       0.50      0.50      0.50     49500
weighted avg       0.85      0.88      0.87     49500

In [43]:
print(len(y[y==1]))
print(len(y[y==0]))

12139
137861

In [44]:
from imblearn.over_sampling import SMOTE as SMO
sampler = SMO()
X,y =  sampler.fit_resample(X,y)

In [46]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [47]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=10)
classifier.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [48]:
print(classifier.score(X_test, y_test, sample_weight=None))
from sklearn.metrics import classification_report
y_pred = classifier.predict(X_test)
print(classification_report(y_true=y_test,y_pred = y_pred))

0.9077690709866028
              precision    recall  f1-score   support

           0       0.88      0.94      0.91     45228
           1       0.94      0.87      0.90     45761

   micro avg       0.91      0.91      0.91     90989
   macro avg       0.91      0.91      0.91     90989
weighted avg       0.91      0.91      0.91     90989